###
#
# Build the demo app and all dependencies
#
# This workflow does not have secrets access
# when run from a fork. Artifacts are uploaded
# and used in a subsequent workflow with more
# privileges which does not run unsafe commands.
#
# https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
#
###

name: Build & Deploy App
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        run: git checkout --orphan gh-pages

      - name: Setup
        uses: swisspost/design-system/.github/actions/setup-pnpm@main

      - name: Install & Build App
        run: |
          pnpm install
          pnpm build

      - name: Deploy App to github pages
        run: |
          git --work-tree dist add --all
          git --work-tree dist commit -m 'Deploy'
          git push origin HEAD:gh-pages --force
          rm -r dist
          git checkout -f main
          git branch -D gh-pages
